name: Line Bot

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_line.txt
    - name: Run script
      run: |
        python test_line.py
      env:
        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
