name: Python application

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      #  pip install -r requirements.txt
        
    # - name: Install font
     # run: sudo apt install fonts-ipafont
    - name: Run script
      run: |
        python main.py
    - name: git setting
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Commit files
      run: |
        git add -N .
